# Site settings
name: "Dushyant Vasoya"
description: "Senior Software Engineer | Full-Stack Developer | Automation Expert"
baseurl: ""
url: "https://DushyantVasoyaUsa.github.io"
theme: jekyll-theme-minimal
